from TableAgent.prompts.answer import ANSWER_SYSTEM_PROMPT, ANSWER_USER_PROMPT_TEMPLATE
from TableAgent.prompts.reranker import RERANKER_SYSTEM_PROMPT, RERANKER_USER_PROMPT_TEMPLATE
from TableAgent.prompts.structure import LAYOUT_MAS_SYSTEM_PROMPT, LAYOUT_MAS_USER_PROMPT_TEMPLATE

__all__ = [
    "ANSWER_SYSTEM_PROMPT",
    "ANSWER_USER_PROMPT_TEMPLATE",
    "LAYOUT_MAS_SYSTEM_PROMPT",
    "LAYOUT_MAS_USER_PROMPT_TEMPLATE",
    "RERANKER_SYSTEM_PROMPT",
    "RERANKER_USER_PROMPT_TEMPLATE",
]
