"""Prompt templates owned by the QA stage."""

from .answer import ANSWER_SYSTEM_PROMPT, ANSWER_USER_PROMPT_TEMPLATE
from .common_info import (
    COMMON_INFO_LOCALIZATION_PROMPT,
    COMMON_INFO_LOCALIZATION_SYSTEM_PROMPT,
)
from .planner import PLANNER_SYSTEM_PROMPT, PLANNER_USER_PROMPT_TEMPLATE
from .react import (
    REACT_SYSTEM_PROMPT,
    REACT_USER_PROMPT_TEMPLATE,
    REVISION_USER_PROMPT_TEMPLATE,
)
from .review import (
    FINAL_ANSWER_REVIEW_SYSTEM_PROMPT,
    FINAL_ANSWER_REVIEW_USER_PROMPT_TEMPLATE,
    REVIEW_SYSTEM_PROMPT,
    REVIEW_USER_PROMPT_TEMPLATE,
)
from .synthesis import (
    SYNTHESIS_REVISION_USER_PROMPT_TEMPLATE,
    SYNTHESIS_SYSTEM_PROMPT,
    SYNTHESIS_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "ANSWER_SYSTEM_PROMPT",
    "ANSWER_USER_PROMPT_TEMPLATE",
    "COMMON_INFO_LOCALIZATION_PROMPT",
    "COMMON_INFO_LOCALIZATION_SYSTEM_PROMPT",
    "FINAL_ANSWER_REVIEW_SYSTEM_PROMPT",
    "FINAL_ANSWER_REVIEW_USER_PROMPT_TEMPLATE",
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_USER_PROMPT_TEMPLATE",
    "REACT_SYSTEM_PROMPT",
    "REACT_USER_PROMPT_TEMPLATE",
    "REVISION_USER_PROMPT_TEMPLATE",
    "REVIEW_SYSTEM_PROMPT",
    "REVIEW_USER_PROMPT_TEMPLATE",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_REVISION_USER_PROMPT_TEMPLATE",
    "SYNTHESIS_USER_PROMPT_TEMPLATE",
]
